language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libcunit1
      - libcunit1-dev 

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install cunit   ; fi

script:
  - make
  - ./tests
  - gcov tests.c

after_success:
  - bash <(curl -s https://codecov.io/bash)


